### ISSUE TITLE
Regex encounters unexpected characters with openevse wifi v2.7.5

### ISSUE THREAD

**Issue by detrout** [miniconfig/python-openevse-wifi#3]
```  File "/usr/lib/python3/dist-packages/homeassistant/components/sensor/openevse.py", line 97, in update
    self._state = float(self.charger.getUsageTotal()) / 1000
  File "~/.homeassistant/deps/lib/python3.5/site-packages/openevsewifi/__init__.py", line 279, in getUsageTotal
    usage = self.sendCommand(command)
  File "~/.homeassistant/deps/lib/python3.5/site-packages/openevsewifi/__init__.py", line 37, in sendCommand
    return response.group(1).split()
AttributeError: 'NoneType' object has no attribute 'group'
```

I tried to manually query the EVSE like this:
```
data = urllib.request.urlopen(c.url + urllib.parse.urlencode({'json':1, 'rapi': '$GS'}))                                 
>>> data.read().decode('utf-8')                                 
'{"cmd":"$GS","ret":"$OK 2 2793^1D"}'  
```

And it looked like the ^1D was confusing the regex.
I found that the javascript in the openevse wifi uses the following regex. "self.regex = /\$([^\^]*)(\^..)?/;"
https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/blob/master/src/html/openevse.js#L70

Which splits the ^hex code into another group.

When I tried to modify openevsewifi I'd found the json argument and used that to simplify parsing which looked like this:

```python
  def sendCommand(self, command):
    """Sends a command through the web interface of the charger and parses the response"""
    data = { 'json': 1, 'rapi' : command }
    full_url = self.url + urllib.parse.urlencode(data)
    data = urllib.request.urlopen(full_url)
    data = json.loads(data.read().decode('utf-8'))
    match = re.search('\$([^\^]*)(\^..)?', data['ret'])
    if match is None:#If we are using version 1 - https://github.com/OpenEVSE/ESP8266_WiFi_v1.x/blob/master/OpenEVSE_RAPI_WiFi_ESP8266.ino#L357
      response = re.search('\>\>\$(.+)\<p>', data.read().decode('utf-8'))
    return response.group(1).split()
```

But I'm not sure how far back the json parameter is supported so I don't know if it'll break with earlier firmwares.

**Comment by jwater7** [comment]
This is a problem for me as well - any reason [the fix](https://github.com/miniconfig/python-openevse-wifi/pull/4) hasn't been merged yet?

**Comment by miniconfig** [comment]
@jwater7 - The problem was that my personal GitHub account, and this project, became severely neglected when I got a new job.  The silver lining in being laid off due to COVID-19, is that now I have time to fix things.  That fix has been merged in, and I have a few others to do over the next few days, at which point I'll upload a new pypi package too.
