### ISSUE TITLE
how to authenticate?

### ISSUE THREAD

**Issue by TonyApuzzo** [miniconfig/python-openevse-wifi#5]
I'm trying to get this working with Home Assistant https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/sensor/openevse.py and it is failing.

I think it is because the newer (2.7.5) WiFi firmware requires login.

I tried setting the host to `user:passwd@hostname` but this doesn't seem to parse. I tried several other permutations like `user:passwd@hostname:80` `user:passwd@hostip:80` etc, but none seem to work with urllib on Python 3.6.

Any advice?  Any chance of getting explicit basic auth support?

Thank you!

**Comment by miniconfig** [comment]
I realize this has taken years, but authentication support has now been added to version 1.1.0
